server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: product-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreakers, metrics
  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  circuitbreaker:
    instances:
      product-service:
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        permitted-number-of-calls-in-same-window: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        automatic-transition-from-open-to-half-open-enabled: true
        event-consumer-buffer-size: 10
  retry:
    instances:
      productServiceRetry:
        max-attempts: 3
        wait-duration: 2s